spring:
  application:
    name: todoapp

  main:
    lazy-initialization: false

  devtools:
    livereload:
      enabled: true

  config:
    import: secrets.yaml

  r2dbc:
    url: r2dbc:postgresql://localhost:54322/postgres
  r2dbc.pool:
    enabled: true
    initial-size: 2
    max-size: 4
    max-idle-time: 5m
    max-life-time: 30h
    validation-query: SELECT 1
    max-validation-time: 1s

  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms:
            - ES256
          # This tells Spring where to fetch the public keys
          jwk-set-uri: http://localhost:54321/auth/v1/.well-known/jwks.json
          # This tells Spring to validate the 'iss' claim in the JWT. Enable once Hosted.
          # issuer-uri: https://<your-project>.supabase.co/auth/v1
          # Optional audience validation
          # audiences: my-api-audience


  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false

server:
  port: 8080

logging:
  level:
    root: info

app:
  logging:
    enabled: true
    max-body-bytes: 4096
